[package]
name = "cargo-cite"
version = "0.1.0"
edition = "2021"

[dependencies]
biblatex = "0.9.3"
cargo-files-core = "0.2.1"
clap = "4.5.16"
clap-cargo = { version = "0.14.1", features = ["cargo_metadata"] }
lazy_static = "1.5.0"
regex = "1.10.6"
